# Generated by Django 4.2 on 2025-11-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
