# Generated by Django 4.2 on 2025-11-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userregister_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('A_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('passw', models.CharField(max_length=25)),
            ],
        ),
    ]
