# Generated by Django 4.2 on 2025-11-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_title', models.CharField(max_length=255)),
                ('c_link', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('c_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('c_img', models.ImageField(upload_to='carousel_images/')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterField(
            model_name='brand',
            name='bimage',
            field=models.ImageField(upload_to='brandimages/'),
        ),
    ]
