# Generated by Django 4.2 on 2025-11-30 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_carousel_alter_brand_bimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('main_image', models.ImageField(upload_to='products/main/')),
                ('thumb_1', models.ImageField(blank=True, null=True, upload_to='products/thumbs/')),
                ('thumb_2', models.ImageField(blank=True, null=True, upload_to='products/thumbs/')),
                ('thumb_3', models.ImageField(blank=True, null=True, upload_to='products/thumbs/')),
                ('thumb_4', models.ImageField(blank=True, null=True, upload_to='products/thumbs/')),
                ('description_html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app.product')),
            ],
        ),
    ]
